import Footer from "./components/Footer/Footer";
import { Header } from "./components/Header/Header";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
